spring:
  banner:
    location: classpath:banner.txt

server:
  port: 8443
  ssl:
    enabled: true
    key-alias: test-cert
    key-store: classpath:identity.jks
    key-store-password: abc123
    key-password: abc123
    trust-store: classpath:truststore.jks
    trust-store-password: secret
    client-auth: need
